import os
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.colors import HexColor
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

PDF_STORAGE_DIR = "storage/pdfs"
os.makedirs(PDF_STORAGE_DIR, exist_ok=True)

class PDFService:
    @staticmethod
    def generate_invoice_pdf(invoice):
        """
        Generates a PDF using ReportLab.
        `invoice` is the SQLAlchemy model representing the bill.
        Returns the relative file path to the saved PDF.
        """
        filename = f"INV-{invoice.invoice_number}-{invoice.id}.pdf"
        filepath = os.path.join(PDF_STORAGE_DIR, filename)
        
        c = canvas.Canvas(filepath, pagesize=letter)
        
        # Use Tenant Brand Color
        brand_color = invoice.tenant.brand_color or "#2563eb"
        try:
            c.setFillColor(HexColor(brand_color))
        except Exception:
            pass
            
        c.setFont("Helvetica-Bold", 16)
        
        # Header
        c.drawString(1 * inch, 10 * inch, f"{invoice.tenant.name.upper()} - INVOICE")
        
        # Draw Logo if exists
        if invoice.tenant.logo_url:
            try:
                c.drawImage(invoice.tenant.logo_url, 6 * inch, 9.5 * inch, width=1.5*inch, height=1*inch, preserveAspectRatio=True, mask='auto')
            except Exception as e:
                print(f"Warning: Could not load tenant logo into PDF: {e}")
                
        # Reset color to black for body text
        c.setFillColor("black")
        
        c.setFont("Helvetica", 12)
        c.drawString(1 * inch, 9.5 * inch, f"Invoice Number: {invoice.invoice_number}")
        c.drawString(1 * inch, 9.25 * inch, f"Due Date: {invoice.due_date.strftime('%Y-%m-%d')}")
        
        # Billed To
        c.drawString(1 * inch, 8.5 * inch, "Billed To:")
        c.drawString(1 * inch, 8.25 * inch, f"Customer: {invoice.customer.name}")
        c.drawString(1 * inch, 8.0 * inch, f"Email: {invoice.customer.email}")
        
        # Line Items (Summary)
        c.drawString(1 * inch, 7.0 * inch, "Usage Summary:")
        y_position = 6.75 * inch
        
        for record in invoice.usage_records:
            line = f"- {record.metric_name}: {record.quantity} units => ${float(record.amount):.2f}"
            c.drawString(1.5 * inch, y_position, line)
            y_position -= 0.25 * inch
            
        # Total
        c.setFont("Helvetica-Bold", 14)
        c.drawString(1 * inch, y_position - 0.5 * inch, f"Total Amount Due: ${float(invoice.amount):.2f}")
        
        c.setFont("Helvetica-Oblique", 10)
        c.drawString(1 * inch, 1 * inch, "Thank you for your business. Generated by Multi-Tenant Invoice Management System.")
        
        c.save()
        return filepath
